### PR TITLE
Add actual color schemes generated via builder

### PR DESCRIPTION
**Pull request by seanwash**
Hey again, I figured this might be useful instead of requiring people to build it themselves.

Hope you're having a great weekend!

### CODE REVIEW

**Comment by seanwash** [comment]
I'm also adding the base16-shell files in here that are needed for 256 color mode, and a small readme for setting this up.

**Comment by kristijanhusak** [comment]
Great! Thanks!

I'm just not sure, what's with the light version? I mean, how does it look? There is no light version for Gvim/MacVim.

**Comment by seanwash** [comment]
It should look like so: http://cl.ly/image/1c1r2S213U3g/Image%202015-08-17%20at%208.36.51%20AM.png

**Comment by kristijanhusak** [comment]
Ok, nice! Thanks!

**Pull request merged**
