### PR TITLE
Add first pass at base16-material

### PR DESCRIPTION
**Pull request by seanwash**
By default I just tossed the whole base16 folder in there, but if you want me to pair it down to just the yaml file I can do that too. Just wanted to get this out since people were asking - it still needs a lot of work.

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Thanks @seanwash .
Can you please just filter out things that are needed? This is really huge.

**Comment by seanwash** [comment]
Yeah, for sure. I'll add a quick readme as well for it. I'm on vaca right now but I'll try to do it soon! @kristijanhusak

**Comment by kristijanhusak** [comment]
No hurry man, just relax, no need to rush, there are many colorschemes out there that will replace this until you come from vacation :)

**Comment by seanwash** [comment]
Hey @kristijanhusak I went through and removed all of the base16 builder files and left only the yaml file that I used to create everything.

**Comment by kristijanhusak** [comment]
Ok, great! That is basically enough to build everything you need. Only readme needs to be updated, but i'll do that when i catch some time. Thank you very much!

**Pull request merged**
